import React from "react";

import devin from "../../assets/profile/Devin.jpg";
import gavin from "../../assets/profile/Gavin.jpg";
import jon from "../../assets/profile/Jon.jpg";
import aadhiya from "../../assets/profile/Aadhiya.jpg";
import parasuraman from "../../assets/profile/Parasuraman.jpg";

import "./about.scss";

const About = () => (
  <div className="about">
    <div className="about-container">
      <h1 className="title">About us</h1>

      <h2 className="sub-title">What is PegHeads.org?</h2>
      <p className="text">
        PegHeads is a full stack web application that's goal is to automate 3D
        animation with Artificial Intelligence.
        We are creating an open source platform for creators to use and showcase
        their independent animations with AI assistance.
        By utilizing AI and a data centric modeling technique this becomes the
        worlds only open source project to automate 3D animations.
        We're a non-profit, so there are no shareholders or VCs in the
        background influencing our decisions here.
        Our income to manage this platform comes from donations and our annual
        revenue is generated by the customers who pay us.
        Thanks to that, we have an unlimited runway to keep building the things
        we want to build and grow this platform with unlimited resources from
        contributions by others.
      </p>

      <br />
      <h2 className="sub-title">Our mission</h2>
      <p className="text">
        We believe there are many creators who have extreme talent in the global
        animation industry. It should be easy and accessible for anyone to
        create their own 3D animation stories assisted by a data centric neural
        network. We're on a mission to create modern, open source, AI technology
        to power the future of sustainable storytelling through 3D animation.
        The days are coming where AI Technolgies will teach humans and we want
        to be the leader in this field.
      </p>

      <br />
      <h2 className="sub-title">How we operate</h2>
      <p className="text">
        We're fans of Basecamp's Shape Up method of product development, and we
        continually review and update how we work. The majority of things here
        get done on Github, with Slack and Zoom for communication.
      </p>

      <br />
      <h2 className="sub-title">Meet Our Team</h2>

      <div className="card-row">
        <div className="card">
          <img src={devin} className="image" alt="devincapriola" />
          <h1 className="name">Devin Capriola</h1>
          <p className="text">
            Enjoy working on ios, android and web. Some of my coding languages
            include: Python, JavaScript & TypeScript. I am thirteen years old
            and looking forward to the continued development & learning while
            creating Pegheads.org.
          </p>
        </div>

        <div className="card">
          <img src={gavin} className="image" alt="gavincapriola" />
          <h1 className="name">Gavin Capriola</h1>
          <p className="text">
            I specialize in web, ios & android development. Additionally have
            experience in numerous coding languages. I’m thirteen years old and
            absolutely love to code.
          </p>
        </div>

        <div className="card">
          <img src={jon} className="image" alt="joncapriola" />
          <h1 className="name">Jon Capriola</h1>
          <p className="text">
            My passion is to create the worlds first educational company that
            uses open source Artificial Intelligence code to automate 3D through
            my own architecture design. This will benefit many globally. For now
            we can use the PegHeads brand but later any 3D animated brand can be
            used. Select your inputs and let AI produce the outputs. That’s the
            goal. After losing my L5 disc and being diagnosed with DDD I took
            the time to focus on my diet and learn as much as I could regarding
            AI and Deep Learning. Since then it seemed right to give back with
            unique characters and an open source technology to automate 3D
            animation. My last invention sold millions of units globally…
            hopefully this innovation will help millions of humans learn all
            Artificial Intelligence. —- Author Inventor dad mentor husband lover
            —- I’m just trying to give back why I still can. Thank you for
            reviewing our site. I hope it benefits you in some way.
          </p>
        </div>

        <div className="card">
          <img src={aadhiya} className="image" alt="aadhiyathomas" />
          <h1 className="name">Aadhiya Thomas</h1>
          <p className="text">
            Professional trainer in coding and AI and APP development. I have
            two years of teaching experience at National Institute of Technology
            Karnataka India,worked on a few projects and published a Paper with
            my students on disaster management using networks. I have worked
            with Whitehat jr and BYJU'S online training platforms to train kids
            on how to code. My main interests are teaching, learning and
            exploring. And looking forward to continue exploring with
            Pegheads.org
          </p>
        </div>

        <div className="card">
          <img src={parasuraman} className="image" alt="parasuraman" />
          <h1 className="name">S. Parasuraman</h1>
          <p className="text">
            I’m a senior executive with 26 years of creative, technical and
            production operations experience in international Animation, Game
            Art and VFX. Founder of a start-up, Vismerize Entertainment Private
            Limited. I enjoy creating a passionate, professional and
            cost-effective work environment through aggressive technical
            optimization, automation and strategic planning. I worked for world
            leading clients like Disney, Warner Brothers, Zag Toons, Method
            Animation and General Electric. My major contributions are for
            iconic shows like Mickey Mouse Club House, Puppy Dog Pals,
            Miraculous Ladybug, The Jungle Book, The New Adventures of Peter
            Pan, Robin Hood: Mischief in Sherwood, and Super4. It’s a great
            pleasure to be part of the highly innovative PegHeads.org team.
          </p>
        </div>
      </div>
    </div>
  </div>
);

export default About;
