import SEO from '@/components/SEO';

export default function About() {
  return <>
  <SEO title="About | PegHeads.org" />
  <div className="mx-auto px-5 sm:px-10 md:px-10 lg:px-30 bg-slate-100 dark:bg-black-900">
    <h1 className="py-8 text-4xl font-extrabold leading-9 tracking-tight sm:text-4xl sm:leading-10 md:text-4xl md:leading-10 text-black-700 dark:text-white">
      About us
    </h1>
  </div>

  <div className="flex flex-col">
    <div className="mx-auto w-full pb-10 px-5 sm:px-10 md:px-10 lg:px-30 bg-slate-100 dark:bg-black-900">
      <h2 className="text-2xl font-extrabold leading-9 tracking-tight sm:text-3xl sm:leading-10 md:text-2xl md:leading-10 text-black-700 dark:text-white">
        What is PegHeads.org?
      </h2>
      <p className="text-sm leading-7 pl-1 pt-5 dark:text-gray-500 text-gray-900">
        PegHeads is a full stack web application that&apos; s goal is to automate 3D animation
        with Artificial Intelligence.We are creating an open source platform for creators to use
        and showcase their independent animations with AI assistance.By utilizing AI and a data
        centric modeling technique this becomes the worlds only open source project to automate
        3D animations.We&apos;re a non-profit, so there are no shareholders or VCs in the
        background influencing our decisions here. Our income to manage this platform comes from
        donations and our annual revenue is generated by the customers who pay us. Thanks to
        that, we have an unlimited runway to keep building the things we want to build and grow
        this platform with unlimited resources from contributions by others.
      </p>
    </div>
    <div className="mx-auto w-full py-10 px-5 sm:px-10 md:px-10 lg:px-30 bg-white dark:bg-black-700">
      <h2 className="text-2xl font-extrabold leading-9 tracking-tight sm:text-3xl sm:leading-10 md:text-2xl md:leading-10 text-black-700 dark:text-white">
        Our Mission
      </h2>
      <p className="text-sm leading-7 pl-1 pt-5 dark:text-gray-500 text-gray-900">
        We believe there are many creators who have extreme talent in the global animation
        industry.It should be easy and accessible for anyone to create their own 3D animation
        stories assisted by a data centric neural network.We&apos;re on a mission to create
        modern, open source, AI technology to power the future of sustainable storytelling
        through 3D animation. The days are coming where AI Technolgies will teach humans and we
        want to be the leader in this field.
      </p>
    </div>
    <div className="mx-auto w-full py-10 px-5 sm:px-10 md:px-10 lg:px-30 bg-slate-100 dark:bg-black-900">
      <h2 className="text-2xl font-extrabold leading-9 tracking-tight sm:text-3xl sm:leading-10 md:text-2xl md:leading-10 text-black-700 dark:text-white">
        How we Operate
      </h2>
      <p className="text-sm leading-7 pl-1 pt-5 dark:text-gray-500 text-gray-900">
        We&apos; re fans of Basecamp&apos;s Shape Up method of product development, and we
        continually review and update how we work. The majority of things here get done on
        Github, with Slack and Zoom for communication.
      </p>
    </div>
    
    {/* TODO */}
    {/* <div className="mx-auto w-full py-10 px-5 sm:px-10 md:px-10 lg:px-30 bg-white dark:bg-black-700">
      <h2 className="text-2xl font-extrabold leading-9 tracking-tight sm:text-3xl sm:leading-10 md:text-2xl md:leading-10 text-black-700 dark:text-white">
        Meet our Team
      </h2>
    </div> */}
  </div>
  </>;
}
